framework:
  messenger:
    failure_transport: failed

    transports:
      async:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        options:
          use_notify: true
          check_delayed_interval: 60000
        retry_strategy:
          max_retries: 3
          multiplier: 2
      failed: "doctrine://default?queue_name=failed"
      # Vous pouvez aussi ajouter un transport "sync" si besoin :
      sync: "sync://"

    default_bus: messenger.bus.default

    buses:
      messenger.bus.default: []

    routing:
      # Utilisation de "sync" pour les e-mails afin qu'ils soient envoyés immédiatement
      Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async

      # Example: Route your messages to the transports
      # 'App\Message\YourMessage': async
