nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:3000'] # Origine autorisée (ton frontend)
    allow_credentials: true
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Link']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
    max_age: 3600
  paths:
    '^/api/':  # Applique la règle à toutes les routes de ton API
      allow_origin: ['http://localhost:3000']
      allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
      allow_headers: ['Content-Type', 'Authorization']
      max_age: 3600
